version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "asana_rebel"
    tty: true
    stdin_open: true
    volumes:
      - .:/asana_rebel
    networks:
      - asana_rebel_net
    ports:
      - "3000:3000"
    links:
      - sidekiq
      - postgres
      - redis
  sidekiq:
    build: .
    command: bundle exe sidekiq -C config/sidekiq.yml
    container_name: "asana_rebel_sidekiq"
    tty: true
    stdin_open: true
    volumes:
      - .:/asana_rebel
    networks:
      - asana_rebel_net
    links:
      - postgres
      - redis
  postgres:
    image: camptocamp/postgres:9.6
    container_name: "asana_rebel_postgres"
    networks:
      - asana_rebel_net
    ports:
      - "5432:5432"
    volumes:
      - asana_rebel_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
  redis:
    image: redis
    container_name: "asana_rebel_redis"
    networks:
      - asana_rebel_net
    ports:
      - "6379:6379"
volumes:
  asana_rebel_vol:
networks:
  asana_rebel_net:
