defaults: &defaults
  cognitive_subscription_key: "It's secret"
  sidekiq:
    redis_uri: "redis://redis:6379/1"
  cache_manager:
    redis_uri: "redis://redis:6379/2"

development:
  <<: *defaults
  database:
    pool: 5
    database: 'asana_rebel_dev'
    host: postgres
    port: 5432
    username: 'ottello'
    password: 'ottello'
  locationiq:
    api_key: pk.fb23abd413baba5eaf0261f4f13902a0
    link: https://eu1.locationiq.com/v1/search.php
    timeout_request_num: 2
    cache_expiration_period_in_minutes: 60 * 24
  search_locations:
    use_db: true

test:
  <<: *defaults
  database:
    pool: 5
    database: 'asana_rebel_test'
    host: postgres
    port: 5432
    username: 'ottello'
    password: 'ottello'
  locationiq:
    api_key: test
    link: https://test.com/v1/search.php
    timeout_request_num: 2
  search_locations:
    use_db: true

production:
  <<: *defaults
  database:
    pool: 5
    database: 'asana_rebel_production'
    host: postgres
    port: 5432
    username: 'ottello'
    password: 'ottello'
