defaults: &defaults
  cognitive_subscription_key: "It's secret"
  sidekiq:
    redis_uri: "redis://redis:6379/1"
  cache_manager:
    redis_uri: "redis://redis:6379/2"

development:
  <<: *defaults
  database:
    pool: 5
    database: 'asana_rebel_dev'
    host: postgres
    port: 5432
    username: 'ottello'
    password: 'ottello'

test:
  <<: *defaults
  database:
    pool: 5
    database: 'asana_rebel_test'
    host: postgres
    port: 5432
    username: 'ottello'
    password: 'ottello'

production:
  <<: *defaults
  database:
    pool: 5
    database: 'asana_rebel_production'
    host: postgres
    port: 5432
    username: 'ottello'
    password: 'ottello'
